apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: todoapp
type: Opaque
stringData:
  NAME: tododb
  USER: root
  PASSWORD: mysecretpassword
  HOST: mysql-0.mysql-service.mysql.svc.cluster.local