apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config-map
  namespace: mysql
data:
  init.sql:  |
    GRANT ALL PRIVILEGES ON app_db.* TO 'app_user'@'%';
    USE app_db;
    CREATE TABLE todos (
        id INT AUTO_INCREMENT PRIMARY KEY,
        value INT
    );