apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config-map
  namespace: mysql
data:
  init.sql:  |
    GRANT ALL PRIVILEGES ON tododb.* TO 'app_user'@'%';
    USE tododb;
    CREATE TABLE todos (
        id INT AUTO_INCREMENT PRIMARY KEY,
        value INT
    );